"""ip to string

Revision ID: 35f0dc7452ce
Revises: 36cdef852157
Create Date: 2014-01-22 14:27:39.063012

"""

# revision identifiers, used by Alembic.
revision = '35f0dc7452ce'
down_revision = '36cdef852157'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
