"""src column

Revision ID: 57ccc3df7de6
Revises: 35f0dc7452ce
Create Date: 2014-01-24 11:43:42.906304

"""

# revision identifiers, used by Alembic.
revision = '57ccc3df7de6'
down_revision = '35f0dc7452ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geoIP', sa.Column('datasrc', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geoIP', 'datasrc')
    ### end Alembic commands ###
